(() => {
  'use strict';
  const D = window.TOEFL_DATA;
  const STORAGE_KEY = 'homemadeToeflProgressV3';
  const ACCESS_KEY = 'homemadeToeflAccessV2';
  const defaultState = () => ({
    version:3, target:5.5, diagnostic:null, stats:{questions:0,correct:0,minutes:0},
    skills:{reading:{done:0,correct:0},listening:{done:0,correct:0},speaking:{done:0,correct:0},writing:{done:0,correct:0}},
    savedWords:[], lastPractice:null, streak:0, activityDates:[]
  });
  let state = loadState();
  let accent = 'en-US';
  let currentTrap = 0;
  let diagIndex = 0, diagAnswers = [], diagLocked = false;
  let readingTab='word', readingIndex=0, academicQuestion=0;
  let listeningTab='response', listeningIndex=0;
  let writingTab='sentence', writingIndex=0, buildSelection=[];
  let mediaRecorder=null, mediaChunks=[], recordingTimer=null, recordingSeconds=0, prepTimeout=null;

  const $ = (s,r=document)=>r.querySelector(s);
  const $$ = (s,r=document)=>[...r.querySelectorAll(s)];
  const esc = s => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

  function loadState(){ try{ const x=JSON.parse(localStorage.getItem(STORAGE_KEY)); return x?mergeState(defaultState(),x):defaultState(); }catch{return defaultState();} }
  function mergeState(a,b){ const out={...a,...b}; out.stats={...a.stats,...(b.stats||{})}; out.skills={}; Object.keys(a.skills).forEach(k=>out.skills[k]={...a.skills[k],...(b.skills?.[k]||{})}); out.savedWords=Array.isArray(b.savedWords)?b.savedWords:[]; out.activityDates=Array.isArray(b.activityDates)?b.activityDates:[]; return out; }
  function saveState(){ saveStateRaw(); updateStreak(); }
  function markActivity(){ const d=new Date().toISOString().slice(0,10); if(!state.activityDates.includes(d)) state.activityDates.push(d); state.activityDates=state.activityDates.slice(-60); updateStreak(); saveStateRaw(); }
  function saveStateRaw(){ try{ localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); }catch{} }
  function updateStreak(){ const dates=[...new Set(state.activityDates)].sort(); let streak=0; if(dates.length){ let d=new Date(); const today=d.toISOString().slice(0,10); const y=new Date(d); y.setDate(y.getDate()-1); const yesterday=y.toISOString().slice(0,10); let cursor=dates.includes(today)?new Date(today):dates.includes(yesterday)?new Date(yesterday):null; if(cursor){ while(true){ const key=cursor.toISOString().slice(0,10); if(dates.includes(key)){ streak++; cursor.setDate(cursor.getDate()-1);} else break; } } } state.streak=streak; saveStateRaw(); }
  function recordQuestion(skill,correct){ state.stats.questions++; if(correct) state.stats.correct++; if(state.skills[skill]){state.skills[skill].done++; if(correct)state.skills[skill].correct++;} markActivity(); updateDashboard(); }
  function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(t._x); t._x=setTimeout(()=>t.classList.remove('show'),2600); }

  // Navigation
  function navigate(view){
    $$('.view').forEach(v=>v.classList.toggle('is-active',v.dataset.view===view));
    $$('.main-nav [data-nav]').forEach(b=>b.classList.toggle('is-active',b.dataset.nav===view));
    $('#mainNav').classList.remove('open'); $('#menuToggle').setAttribute('aria-expanded','false');
    history.replaceState(null,'','#'+view); window.scrollTo({top:0,behavior:document.documentElement.classList.contains('reduce-motion')?'auto':'smooth'});
    if(view==='dashboard')updateDashboard(); if(view==='vocabulary')renderVocabulary();
  }
  $$('[data-nav]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.nav)));
  $('#menuToggle').addEventListener('click',()=>{const n=$('#mainNav');const o=n.classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',o)});
  const initial=location.hash.replace('#',''); if($(`[data-view="${initial}"]`)) navigate(initial);

  // Accent + speech
  $$('.accent-choice').forEach(b=>b.addEventListener('click',()=>{$$('.accent-choice').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');accent=b.dataset.accent;toast(`${b.textContent.trim()} voice selected`)}));
  function speak(text,rate=.94){ if(!('speechSynthesis' in window)){toast('Text-to-speech is not available on this device.');return;} speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang=accent;u.rate=rate; const voices=speechSynthesis.getVoices(); const preferred=voices.find(v=>v.lang===accent)||voices.find(v=>v.lang.startsWith(accent.slice(0,2)));if(preferred)u.voice=preferred;speechSynthesis.speak(u); }

  // Daily trap
  function renderTrap(){ const t=D.traps[currentTrap%D.traps.length];$('#trapTitle').textContent=t.title;$('#trapPrompt').textContent=t.prompt;$('#trapFeedback').textContent='';$('#trapFeedback').className='feedback';const box=$('#trapOptions');box.innerHTML='';t.options.forEach((o,i)=>{const b=document.createElement('button');b.textContent=o;b.onclick=()=>{if(box.dataset.locked==='1')return;box.dataset.locked='1';[...box.children].forEach((x,j)=>{ if(j===t.answer)x.classList.add('correct'); else if(j===i)x.classList.add('wrong'); });$('#trapFeedback').textContent=t.explanation;$('#trapFeedback').classList.add(i===t.answer?'good':'bad');recordQuestion('writing',i===t.answer)};box.appendChild(b)});box.dataset.locked='0'; }
  $('#nextTrap').onclick=()=>{currentTrap=(currentTrap+1)%D.traps.length;renderTrap()};renderTrap();

  // Diagnostic
  $('#startDiagnostic').onclick=()=>{diagIndex=0;diagAnswers=[];$('#diagIntro').classList.add('hidden');$('#diagResult').classList.add('hidden');$('#diagRunner').classList.remove('hidden');renderDiag()};
  function renderDiag(){diagLocked=false;const item=D.diagnostic[diagIndex];$('#diagSkill').textContent=item.skill.toUpperCase();$('#diagCount').textContent=`${diagIndex+1} / ${D.diagnostic.length}`;$('#diagProgress').style.width=`${(diagIndex/D.diagnostic.length)*100}%`;$('#diagQuestion').textContent=item.q;const stim=$('#diagStimulus');stim.innerHTML='';if(item.type==='audio'){stim.innerHTML=`<div class="listen-box"><button class="speaker" type="button">▶ Listen</button><span>Listen to the extract, then answer.</span></div>`;$('.speaker',stim).onclick=()=>speak(item.audio,.92)}else if(item.stimulus){stim.innerHTML=`<div class="stimulus">${esc(item.stimulus)}</div>`} const ans=$('#diagAnswers');ans.innerHTML='';item.options.forEach((o,i)=>{const b=document.createElement('button');b.textContent=o;b.onclick=()=>answerDiag(i,b);ans.appendChild(b)});$('#diagFeedback').textContent='';$('#diagFeedback').className='feedback';$('#diagNext').textContent=diagIndex===D.diagnostic.length-1?'See results →':'Next →';$('#diagNext').classList.add('hidden');}
  function answerDiag(i,b){if(diagLocked)return;diagLocked=true;const item=D.diagnostic[diagIndex],ok=i===item.answer;diagAnswers.push({skill:item.skill,ok});[...$('#diagAnswers').children].forEach((x,j)=>{ if(j===item.answer)x.classList.add('correct'); else if(j===i)x.classList.add('wrong'); });$('#diagFeedback').textContent=(ok?'✓ ':'✗ ')+item.why;$('#diagFeedback').classList.add(ok?'good':'bad');$('#diagNext').classList.remove('hidden');}
  $('#diagNext').onclick=()=>{diagIndex++;if(diagIndex<D.diagnostic.length)renderDiag();else finishDiag()};
  function bandFromPct(p){if(p>=1)return 6;if(p>=.95)return 5.5;if(p>=.875)return 5;if(p>=.75)return 4.5;if(p>=.65)return 4;if(p>=.55)return 3.5;return 3;}
  function finishDiag(){const by={reading:[],listening:[],speaking:[],writing:[]};diagAnswers.forEach(a=>by[a.skill].push(a.ok));const skills={};Object.keys(by).forEach(k=>{const c=by[k].filter(Boolean).length;skills[k]={correct:c,total:by[k].length,pct:c/by[k].length,band:bandFromPct(c/by[k].length)}});const avg=Object.values(skills).reduce((s,x)=>s+x.band,0)/4;const overall=Math.round(avg*2)/2;state.diagnostic={date:new Date().toISOString(),overall,skills};state.stats.questions+=D.diagnostic.length;state.stats.correct+=diagAnswers.filter(x=>x.ok).length;Object.keys(skills).forEach(k=>{state.skills[k].done+=skills[k].total;state.skills[k].correct+=skills[k].correct});markActivity();$('#diagRunner').classList.add('hidden');const r=$('#diagResult');r.classList.remove('hidden');const level=overall>=6?'C2':overall>=5?'C1':overall>=4?'B2':'B1';r.innerHTML=`<div class="result-hero"><span>Pedagogical estimate</span><strong>${overall.toFixed(1)}</strong><h2>${level} · ${overall>=5?'C-level range on this diagnostic':'below the C-level range'}</h2><p>This result is an internal practice estimate only. It is not an ETS score.</p></div><div class="result-grid">${Object.entries(skills).map(([k,v])=>`<article class="result-skill"><h3>${cap(k)}</h3><strong>${v.band.toFixed(1)}</strong><p>${v.correct}/${v.total} correct answers</p><button class="text-btn" data-go="${k}">Practise ${cap(k)} →</button></article>`).join('')}</div><div class="cta-row"><button class="btn primary" data-go="dashboard">View my recommended route</button><button class="btn secondary" id="redoDiag">Retake the diagnostic</button></div>`;$$('[data-go]',r).forEach(x=>x.onclick=()=>navigate(x.dataset.go));$('#redoDiag').onclick=()=>$('#startDiagnostic').click();updateDashboard();}

  // Dashboard
  function skillBand(skill){if(state.diagnostic?.skills?.[skill])return state.diagnostic.skills[skill].band;const s=state.skills[skill];return s.done?bandFromPct(s.correct/s.done):0;}
  function updateDashboard(){updateStreak();const overall=state.diagnostic?.overall||0;$('#overallBand').textContent=overall?overall.toFixed(1):'—';$('#overallCefr').textContent=overall?(overall>=6?'C2':overall>=5?'C1':overall>=4?'B2':'B1'):'Take the diagnostic';$('#targetBand').value=String(state.target||5.5);$('#streakValue').textContent=state.streak||0;$('#questionsDone').textContent=state.stats.questions||0;$('#savedWordsCount').textContent=state.savedWords.length;$('#practiceMinutes').textContent=state.stats.minutes||0;const box=$('#skillDashboard');box.innerHTML=['reading','listening','speaking','writing'].map(k=>{const b=skillBand(k),pct=Math.max(0,Math.min(100,(b/6)*100));const stat=state.skills[k];return `<article class="skill-meter"><header><h3>${cap(k)}</h3><strong>${b?b.toFixed(1):'—'}</strong></header><div class="meter"><span style="width:${pct}%"></span></div><small>${stat.done?Math.round(stat.correct/stat.done*100)+'% practice accuracy':'No practice data yet'}</small><button class="text-btn" data-route="${k}">Practise →</button></article>`}).join('');$$('[data-route]',box).forEach(b=>b.onclick=()=>navigate(b.dataset.route));const route=['reading','listening','speaking','writing'].map(k=>({k,b:skillBand(k)})).sort((a,b)=>(a.b||0)-(b.b||0));$('#recommendedRoute').innerHTML=`<div class="route-list">${route.map((x,i)=>`<div class="route-item"><div><span class="priority">${i===0?'PRIORITY':'STEP '+(i+1)}</span> <strong>${cap(x.k)}</strong><p>${routeTip(x.k,x.b)}</p></div><button class="btn secondary small" data-route2="${x.k}">Open</button></div>`).join('')}</div>`;$$('[data-route2]').forEach(b=>b.onclick=()=>navigate(b.dataset.route2));}
  function routeTip(k,b){const tips={reading:'Train inference, rhetorical structure, reference, scope and vocabulary in context.',listening:'Track contrast, implication, detail function and speaker stance.',speaking:'Build direct answers, controlled qualification, reformulation and prosodic clarity.',writing:'Strengthen precision, cohesion, synthesis, paraphrase and register control.'};return `${tips[k]} ${b?`Current estimate: ${b.toFixed(1)}.`:'Start here to generate practice data.'}`}
  $('#saveTarget').onclick=()=>{state.target=Number($('#targetBand').value);saveState();toast('Target saved')};

  // Tabs generic
  $$('[data-tabs="reading"] button').forEach(b=>b.onclick=()=>{readingTab=b.dataset.tab;readingIndex=0;academicQuestion=0;$$('[data-tabs="reading"] button').forEach(x=>x.classList.toggle('is-active',x===b));renderReading()});
  function renderReading(){const w=$('#readingWorkspace');if(readingTab==='word'){const x=D.reading.word[readingIndex%D.reading.word.length];w.innerHTML=practiceMCQ('Complete the Words',`<p class="cloze-word">${esc(x.stem)}</p>`,x.options,x.answer,x.why,'reading','nextReading');}
    else if(readingTab==='daily'){const x=D.reading.daily[readingIndex%D.reading.daily.length];w.innerHTML=practiceMCQ('Read in Daily Life',`<div class="passage">${esc(x.text)}</div><h3>${esc(x.q)}</h3>`,x.options,x.answer,x.why,'reading','nextReading');}
    else {const p=D.reading.academic[readingIndex%D.reading.academic.length],q=p.questions[academicQuestion%p.questions.length];w.innerHTML=practiceMCQ(p.title,`<div class="passage">${esc(p.text).replace(/\n\n/g,'<br><br>')}</div><h3>${esc(q.q)}</h3>`,q.options,q.answer,q.why,'reading','nextAcademic');} wirePractice(w);}
  function practiceMCQ(title,stim,opts,ans,why,skill,nextId){return `<article class="practice-card" data-answer="${ans}" data-skill="${skill}" data-why="${esc(why)}"><span class="tag teal">${cap(skill)}</span><h2>${esc(title)}</h2>${stim}<div class="choice-row">${opts.map((o,i)=>`<button data-choice="${i}">${esc(o)}</button>`).join('')}</div><div class="feedback"></div><div class="question-nav"><span></span><button class="btn primary hidden" id="${nextId}">Next →</button></div></article>`}
  function wirePractice(root){const card=$('.practice-card',root);if(!card)return;$$('[data-choice]',card).forEach(b=>b.onclick=()=>{if(card.dataset.locked)return;card.dataset.locked='1';const a=Number(card.dataset.answer),i=Number(b.dataset.choice),ok=i===a;$$('[data-choice]',card).forEach((x,j)=>{ if(j===a)x.classList.add('correct'); else if(j===i)x.classList.add('wrong'); });const f=$('.feedback',card);f.textContent=(ok?'✓ ':'✗ ')+card.dataset.why;f.classList.add(ok?'good':'bad');recordQuestion(card.dataset.skill,ok);const next=$('.question-nav .btn',card);next.classList.remove('hidden');next.onclick=()=>advancePractice(next.id);});}
  function advancePractice(id){if(id==='nextReading'){readingIndex++;renderReading()}else if(id==='nextAcademic'){const p=D.reading.academic[readingIndex%D.reading.academic.length];academicQuestion++;if(academicQuestion>=p.questions.length){academicQuestion=0;readingIndex++;}renderReading()}else if(id==='nextListening'){listeningIndex++;renderListening()}else if(id==='nextLab'){renderLab(currentLab,true)}}
  renderReading();

  // Listening
  $$('[data-tabs="listening"] button').forEach(b=>b.onclick=()=>{listeningTab=b.dataset.tab;listeningIndex=0;$$('[data-tabs="listening"] button').forEach(x=>x.classList.toggle('is-active',x===b));renderListening()});
  function renderListening(){const arr=D.listening[listeningTab],x=arr[listeningIndex%arr.length];const title={response:'Listen and Choose a Response',conversation:'Conversation',announcement:'Announcement',talk:'Academic Talk'}[listeningTab];const q=x.q||'Choose the most appropriate response.';const w=$('#listeningWorkspace');w.innerHTML=practiceMCQ(title,`<div class="listen-box"><button class="speaker" type="button">▶ Listen</button><span>${esc(q)}</span></div>`,x.options,x.answer,x.why,'listening','nextListening');$('.speaker',w).onclick=()=>speak(x.audio,listeningTab==='talk'?.89:.93);wirePractice(w);}
  renderListening();

  // Speaking
  let repeatIdx=0, interviewIdx=0;
  function loadRepeat(){const x=D.speaking.repeat[repeatIdx%D.speaking.repeat.length];$('#repeatSentence').textContent=x;return x} $('#newRepeat').onclick=()=>{repeatIdx++;loadRepeat()};$('#playRepeat').onclick=()=>speak(loadRepeat(),.9);loadRepeat();
  function loadInterview(){const x=D.speaking.interview[interviewIdx%D.speaking.interview.length];$('#interviewQuestion').textContent=x.q;$('#interviewFollowup').textContent=x.follow;return x} $('#newInterview').onclick=()=>{interviewIdx++;loadInterview()};loadInterview();
  $('#startRecording').onclick=async()=>{if(!navigator.mediaDevices?.getUserMedia){toast('Microphone recording is not available in this browser.');return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)mediaChunks.push(e.data)};mediaRecorder.onstop=()=>{const blob=new Blob(mediaChunks,{type:mediaRecorder.mimeType||'audio/webm'});const audio=$('#recordingPlayback');audio.src=URL.createObjectURL(blob);audio.classList.remove('hidden');stream.getTracks().forEach(t=>t.stop());state.stats.minutes+=1;markActivity();updateDashboard()};$('#startRecording').disabled=true;$('#speakTimer').textContent='PREP 15';let prep=15;prepTimeout=setInterval(()=>{prep--;$('#speakTimer').textContent=`PREP ${String(prep).padStart(2,'0')}`;if(prep<=0){clearInterval(prepTimeout);startActualRecording();}},1000);}catch{toast('Microphone permission was denied or is unavailable.')}};
  function startActualRecording(){recordingSeconds=0;mediaRecorder.start();$('#stopRecording').classList.remove('hidden');$('#speakTimer').textContent='00:00';recordingTimer=setInterval(()=>{recordingSeconds++;$('#speakTimer').textContent=`${String(Math.floor(recordingSeconds/60)).padStart(2,'0')}:${String(recordingSeconds%60).padStart(2,'0')}`;if(recordingSeconds>=60)stopRec();},1000)}
  function stopRec(){clearInterval(recordingTimer);if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();$('#stopRecording').classList.add('hidden');$('#startRecording').disabled=false} $('#stopRecording').onclick=stopRec;

  // Writing
  $$('[data-tabs="writing"] button').forEach(b=>b.onclick=()=>{writingTab=b.dataset.tab;writingIndex=0;buildSelection=[];$$('[data-tabs="writing"] button').forEach(x=>x.classList.toggle('is-active',x===b));renderWriting()});
  function renderWriting(){const w=$('#writingWorkspace');if(writingTab==='sentence')renderBuild(w);else if(writingTab==='email')renderLongWriting(w,'email');else renderLongWriting(w,'discussion');}
  function renderBuild(w){const x=D.writing.sentence[writingIndex%D.writing.sentence.length];buildSelection=[];w.innerHTML=`<article class="practice-card"><span class="tag teal">BUILD A SENTENCE</span><h2>Build a precise sentence</h2><p>Click the chunks in the correct order. Capitalisation and punctuation will be normalised for comparison.</p><div class="build-words">${shuffle(x.words.map((v,i)=>({v,i}))).map(o=>`<button class="word-chip" data-original="${o.i}">${esc(o.v)}</button>`).join('')}</div><div class="sentence-build" id="sentenceBuild"></div><div class="feedback" id="buildFeedback"></div><div class="cta-row"><button class="btn secondary" id="clearBuild">Clear</button><button class="btn primary" id="checkBuild">Check</button><button class="btn primary hidden" id="nextBuild">Next →</button></div></article>`;$$('.word-chip',w).forEach(b=>b.onclick=()=>{buildSelection.push(b.textContent);b.disabled=true;const c=document.createElement('button');c.className='word-chip';c.textContent=b.textContent;c.onclick=()=>{const idx=buildSelection.indexOf(c.textContent);if(idx>-1)buildSelection.splice(idx,1);b.disabled=false;c.remove()};$('#sentenceBuild').appendChild(c)});$('#clearBuild').onclick=()=>renderBuild(w);$('#checkBuild').onclick=()=>{const built=normaliseSentence(buildSelection.join(' ')),ans=normaliseSentence(x.answer),ok=built===ans;$('#buildFeedback').textContent=ok?'✓ Correct.':`✗ Model: ${x.answer}`;$('#buildFeedback').className='feedback '+(ok?'good':'bad');recordQuestion('writing',ok);$('#nextBuild').classList.remove('hidden')};$('#nextBuild').onclick=()=>{writingIndex++;renderBuild(w)}}
  function normaliseSentence(s){return s.toLowerCase().replace(/[.,!?]/g,'').replace(/\s+/g,' ').trim()}
  function renderLongWriting(w,type){const arr=D.writing[type],x=arr[writingIndex%arr.length];let prompt='';if(type==='email')prompt=`<p><strong>Situation:</strong> ${esc(x.situation)}</p><div class="score-banner"><span>Recipient: ${esc(x.recipient)}</span><span>Goal: ${esc(x.goal)}</span></div>`;else prompt=`<div class="stimulus"><p>${esc(x.teacher)}</p><p><strong>Student A:</strong> ${esc(x.studentA)}</p><p><strong>Student B:</strong> ${esc(x.studentB)}</p></div><p><strong>Your task:</strong> ${esc(x.prompt)}</p>`;w.innerHTML=`<article class="practice-card"><span class="tag coral">${type==='email'?'WRITE AN EMAIL':'ACADEMIC DISCUSSION'}</span><h2>${type==='email'?'Write a concise, appropriate email':'Join the discussion'}</h2>${prompt}<div class="timer-display" id="writeTimer">${type==='email'?'07:00':'10:00'}</div><textarea class="writing-area" id="writingArea" placeholder="Write here…"></textarea><div class="word-counter"><span id="wordCount">0</span> words</div><div class="cta-row"><button class="btn secondary" id="startWriteTimer">▶ Start timer</button><button class="btn primary" id="finishWriting">Finish & self-check</button><button class="btn secondary hidden" id="nextWriting">Next prompt</button></div><div id="writingCheck" class="hidden"></div></article>`;let remaining=(type==='email'?7:10)*60,timer=null;const ta=$('#writingArea');ta.oninput=()=>$('#wordCount').textContent=countWords(ta.value);$('#startWriteTimer').onclick=()=>{if(timer)return;timer=setInterval(()=>{remaining--;$('#writeTimer').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;if(remaining<=0)clearInterval(timer)},1000)};$('#finishWriting').onclick=()=>{if(timer)clearInterval(timer);state.stats.minutes+=type==='email'?7:10;markActivity();$('#writingCheck').classList.remove('hidden');$('#writingCheck').innerHTML=`<div class="rubric-grid"><label><input type="checkbox"> I answered the exact task.</label><label><input type="checkbox"> My ideas are clearly connected.</label><label><input type="checkbox"> My register fits the context.</label><label><input type="checkbox"> I used precise, varied language.</label><label><input type="checkbox"> I qualified claims where needed.</label><label><input type="checkbox"> I checked grammar and word forms.</label></div><details class="model-box"><summary><strong>Show a possible C-level model</strong></summary><p style="white-space:pre-line">${esc(x.model)}</p></details>`;$('#nextWriting').classList.remove('hidden')};$('#nextWriting').onclick=()=>{writingIndex++;renderLongWriting(w,type)}}
  function countWords(s){return (s.trim().match(/\b[\w’'-]+\b/g)||[]).length} renderWriting();

  // Vocabulary
  function renderVocabulary(savedOnly=false){const q=($('#vocabSearch')?.value||'').toLowerCase().trim();const list=D.vocabulary.filter(v=>(!savedOnly||state.savedWords.includes(v[0]))&&(!q||v.join(' ').toLowerCase().includes(q)));const grid=$('#vocabGrid');if(!grid)return;grid.innerHTML=list.length?list.map(v=>`<article class="vocab-card"><h3>${esc(v[0])}</h3><div class="ipa">${esc(v[1])}</div><p>${esc(v[2])}</p><p class="usage"><strong>Use:</strong> ${esc(v[3])}</p><p><em>${esc(v[4])}</em></p><div class="vocab-actions"><button data-say="${esc(v[0])}">🔊 Listen</button><button data-word="${esc(v[0])}">${state.savedWords.includes(v[0])?'★ Saved':'☆ My Words'}</button></div></article>`).join(''):'<div class="card"><p>No words match this filter.</p></div>';$$('[data-say]',grid).forEach(b=>b.onclick=()=>speak(b.dataset.say,.85));$$('[data-word]',grid).forEach(b=>b.onclick=()=>toggleWord(b.dataset.word,savedOnly));}
  function toggleWord(w,savedOnly){const i=state.savedWords.indexOf(w);if(i>=0)state.savedWords.splice(i,1);else state.savedWords.push(w);saveState();renderVocabulary(savedOnly);updateDashboard();toast(i>=0?'Removed from My Words':'Added to My Words')}
  $('#vocabSearch').oninput=()=>renderVocabulary(false);let savedOnly=false;$('#showSavedWords').onclick=()=>{savedOnly=!savedOnly;$('#showSavedWords').textContent=savedOnly?'📚 All words':'⭐ My Words';renderVocabulary(savedOnly)};renderVocabulary();

  // C-Level Lab
  let currentLab='hedging',labIndex=0;$$('[data-lab]').forEach(b=>b.onclick=()=>{currentLab=b.dataset.lab;labIndex=0;renderLab(currentLab);$('#labWorkspace').scrollIntoView({behavior:'smooth',block:'center'})});
  function renderLab(key,advance=false){if(advance)labIndex++;const arr=D.lab[key],x=arr[labIndex%arr.length];const names={hedging:'Hedging & caution',nominalisation:'Nominalisation',complex:'Complex sentences',paraphrase:'Paraphrase',stance:'Stance & evaluation',cohesion:'Cohesion'};const w=$('#labWorkspace');w.innerHTML=practiceMCQ(names[key],`<h3>${esc(x.q)}</h3>`,x.options,x.answer,x.why,'writing','nextLab');wirePractice(w)}

  // Home mini-games route into existing trainers
  $$('[data-drill]').forEach(b=>b.onclick=()=>{const d=b.dataset.drill;if(d==='inference'){readingTab='academic';$$('[data-tabs="reading"] button').forEach(x=>x.classList.toggle('is-active',x.dataset.tab==='academic'));navigate('reading');renderReading()}else if(d==='hedging'){navigate('clevel');currentLab='hedging';renderLab('hedging')}else{listeningTab='talk';$$('[data-tabs="listening"] button').forEach(x=>x.classList.toggle('is-active',x.dataset.tab==='talk'));navigate('listening');renderListening()}});

  // Accessibility
  function loadAccess(){let a={};try{a=JSON.parse(localStorage.getItem(ACCESS_KEY)||'{}')}catch{};applyAccess(a);$('#highContrast').checked=!!a.highContrast;$('#readableFont').checked=!!a.readableFont;$('#reduceMotion').checked=!!a.reduceMotion;$('#focusMode').checked=!!a.focusMode;}
  function applyAccess(a){const h=document.documentElement;h.classList.toggle('high-contrast',!!a.highContrast);h.classList.toggle('readable-font',!!a.readableFont);h.classList.toggle('reduce-motion',!!a.reduceMotion);h.classList.toggle('focus-mode',!!a.focusMode);h.classList.remove('font-large','font-xlarge');if(a.font==='large')h.classList.add('font-large');if(a.font==='xlarge')h.classList.add('font-xlarge')}
  function saveAccess(){const a={highContrast:$('#highContrast').checked,readableFont:$('#readableFont').checked,reduceMotion:$('#reduceMotion').checked,focusMode:$('#focusMode').checked,font:document.documentElement.classList.contains('font-xlarge')?'xlarge':document.documentElement.classList.contains('font-large')?'large':'normal'};try{localStorage.setItem(ACCESS_KEY,JSON.stringify(a));}catch{}applyAccess(a)}
  $('#accessibilityBtn').onclick=()=>$('#accessibilityModal').classList.remove('hidden');$('#closeAccess').onclick=()=>$('#accessibilityModal').classList.add('hidden');['highContrast','readableFont','reduceMotion','focusMode'].forEach(id=>$('#'+id).onchange=saveAccess);$$('[data-font]').forEach(b=>b.onclick=()=>{document.documentElement.classList.remove('font-large','font-xlarge');if(b.dataset.font==='large')document.documentElement.classList.add('font-large');if(b.dataset.font==='xlarge')document.documentElement.classList.add('font-xlarge');saveAccess()});loadAccess();

  // Export/import
  function exportProgress(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`homemade-toefl-progress-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
  async function importProgress(file){if(!file)return;try{const x=JSON.parse(await file.text());state=mergeState(defaultState(),x);saveState();updateDashboard();renderVocabulary();toast('Progress imported')}catch{toast('Invalid progress file')}}
  $('#exportProgress').onclick=exportProgress;$('#exportProgressModal').onclick=exportProgress;$('#importProgress').onchange=e=>importProgress(e.target.files[0]);$('#importProgressModal').onchange=e=>importProgress(e.target.files[0]);$('#resetProgress').onclick=()=>{if(confirm('Delete all progress saved on this device?')){state=defaultState();saveState();updateDashboard();renderVocabulary();toast('Progress reset')}};
  $('#saveBtn').onclick=()=>$('#saveModal').classList.remove('hidden');$('#closeSave').onclick=()=>$('#saveModal').classList.add('hidden');
  $$('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));

  // Utilities
  function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
  function shuffle(a){return a.map(x=>({x,r:Math.random()})).sort((a,b)=>a.r-b.r).map(o=>o.x)}
  updateDashboard();
})();
