(() => {
  'use strict';
  const D=window.CPLUS_DATA;
  if(!D)return;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const KEY='homemadeCPlusV1';
  const defaults=()=>({version:1,plan:null,completed:{},portfolio:[],onlineIndex:0,mediationIndex:0});
  function merge(raw){const s=defaults();if(!raw||typeof raw!=='object')return s;s.plan=raw.plan&&typeof raw.plan==='object'?raw.plan:null;s.completed=raw.completed&&typeof raw.completed==='object'?raw.completed:{};s.portfolio=(Array.isArray(raw.portfolio)?raw.portfolio:[]).slice(-30).map(x=>({id:String(x?.id||''),type:['Online Interaction','Mediation','Mission','TOEFL Writing','TOEFL Speaking','C-Level Mission','Other'].includes(x?.type)?x.type:'Other',title:String(x?.title||''),dimensions:Array.isArray(x?.dimensions)?x.dimensions.map(String).slice(0,4):[],first:String(x?.first||''),revised:String(x?.revised||''),reflection:String(x?.reflection||''),score:x?.score==null?null:Math.max(0,Math.min(6,Number(x.score)||0)),date:String(x?.date||'')}));s.onlineIndex=Math.max(0,Math.floor(Number(raw.onlineIndex)||0));s.mediationIndex=Math.max(0,Math.floor(Number(raw.mediationIndex)||0));return s;}
  function load(){try{return merge(JSON.parse(localStorage.getItem(KEY)||'null'))}catch{return defaults()}}
  let state=load();
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}renderAll();window.TOEFL_APP?.refresh?.();}
  function toefl(){return window.TOEFL_APP?.getState?.()||{};}
  function clevel(){return window.CLEVEL_APP?.exportState?.()||{};}
  function recentAcc(x){const a=Array.isArray(x?.recent)?x.recent.slice(-8):[];if(a.length>=3)return a.filter(Boolean).length/a.length;if(Number(x?.done)>0)return Number(x.correct||0)/Number(x.done);return null;}
  function weakToefl(){return Object.values(toefl().errorLog||{}).filter(x=>Number(x.done)>=2).map(x=>({...x,acc:recentAcc(x)})).filter(x=>x.acc!=null).sort((a,b)=>a.acc-b.acc||Number(b.done)-Number(a.done));}
  function weakC(){const s=clevel();return (window.CLEVEL_DATA?.dimensions||[]).map(d=>({key:d.key,title:d.title,icon:d.icon,acc:recentAcc(s.skills?.[d.key])})).filter(x=>x.acc!=null).sort((a,b)=>a.acc-b.acc);}
  function nav(view,anchor){if(window.TOEFL_APP?.navigate)window.TOEFL_APP.navigate(view);else document.querySelector(`[data-nav="${view}"]`)?.click();if(anchor)setTimeout(()=>document.querySelector(anchor)?.scrollIntoView({behavior:'smooth',block:'start'}),60);}
  function localDay(){const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10);}
  function tomorrowDay(){const d=new Date();d.setDate(d.getDate()+1);const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10);}

  // ---------- CEFR-informed descriptor map ----------
  function renderCefr(){const box=$('#cefrMap');if(!box)return;const cs=clevel();box.innerHTML=D.cefr.map(d=>{const objective=d.key==='online'?null:recentAcc(cs.skills?.[d.key]);const portfolio=state.portfolio.filter(x=>x.dimensions.includes(d.key)).length;return `<article class="cefr-card"><div class="cefr-card-head"><span>${d.icon}</span><div><h3>${esc(d.title)}</h3><small>${esc(d.official)}</small></div></div><p>${esc(d.canDo)}</p><div class="cefr-evidence"><span>${objective==null?'—':Math.round(objective*100)+'%'} objective</span><span>${portfolio} portfolio evidence</span></div><details><summary>Evidence on this site</summary><ul>${d.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details></article>`}).join('');}

  // ---------- Study plan ----------
  function plannedWeeksFromDate(v){if(!v)return 6;const end=new Date(v+'T12:00:00'),now=new Date();const days=Math.ceil((end-now)/86400000);if(!Number.isFinite(days)||days<=7)return 1;return Math.max(1,Math.min(8,Math.ceil(days/7)));}
  function buildPlan(){const date=$('#planTestDate')?.value||'';if(date&&date<tomorrowDay()){const box=$('#studyPlanOutput');if(box)box.innerHTML='<div class="feedback bad">Choose a future TOEFL test date, or leave the date blank for a rolling six-week plan.</div>';return;}const sessions=Math.max(2,Math.min(4,Number($('#planSessions')?.value)||3)),focus=$('#planFocus')?.value||'balanced',target=$('#planTarget')?.value||'5.5',weeks=plannedWeeksFromDate(date);const tw=weakToefl(),cw=weakC();const t1=tw[0],t2=tw[1],c1=cw[0],c2=cw[1];const pool=[];
    const add=(title,note,route,duration=30)=>pool.push({title,note,route,duration});
    if(focus!=='clevel'){
      if(t1)add(`Recycle: ${D.recyclerLabels[t1.category]||t1.category}`,`Fresh ${t1.skill} item targeting a recurring weakness.`,`weak:${t1.skill}|${t1.category}`,25);
      if(t2)add(`Recycle: ${D.recyclerLabels[t2.category]||t2.category}`,`A second weak pattern, trained with a fresh item.`,`weak:${t2.skill}|${t2.category}`,25);
      add('TOEFL objective set','One focused Reading or Listening set in exam conditions.','nav:test',35);
      add('Timed productive practice','Do one Speaking or Writing task, self-review it, then revise one weakness.','nav:writing',35);
      add('Practice simulation','Run the focused non-adaptive simulation without feedback until the end.','nav:test',45);
    }
    if(focus!=='toefl'){
      add(c1?`Reach C Level: ${c1.title}`:'Reach C Level: objective control',c1?'Train your weakest measured C-level dimension.':'Build objective C-level control.','clevel:'+(c1?.key||'nuance'),30);
      add(c2?`Reach C Level: ${c2.title}`:'Upgrade Machine',c2?'Train your second weakest measured dimension.':'Upgrade accurate B2 English into more controlled C-level English.','clevel:'+(c2?.key||'precision'),30);
      add('Online Interaction Studio','Integrate other people’s contributions, repair a misunderstanding and move the exchange forward.','cplus:online',35);
      add('Mediation Studio','Restructure complex meaning for a different audience without distorting it.','cplus:mediation',35);
      add('Portfolio revision','Take one saved first attempt and produce a more controlled second version.','cplus:portfolio',25);
    }
    if(!pool.length)add('Reach C Level','Complete one objective lab and one productive mission.','nav:reachc',35);
    const sessionsOut=[];let p=0;for(let w=1;w<=weeks;w++){for(let j=1;j<=sessions;j++){const item=pool[p++%pool.length];sessionsOut.push({id:`w${w}s${j}`,week:w,session:j,...item});}}
    state.plan={created:new Date().toISOString(),date,sessions,focus,target,weeks,items:sessionsOut};state.completed={};save();}
  function renderPlan(){const box=$('#studyPlanOutput');if(!box)return;const p=state.plan;if(!p){box.innerHTML='<div class="empty-state">Generate a plan and it will stay on this device. It uses your current TOEFL error log and C-Level profile when enough evidence exists.</div>';return;}const done=p.items.filter(x=>state.completed[x.id]).length;box.innerHTML=`<div class="plan-summary"><div><strong>${done}/${p.items.length}</strong><span>sessions completed</span></div><div><strong>${p.weeks}</strong><span>week rolling plan</span></div><div><strong>${esc(p.target)}</strong><span>target</span></div></div><div class="plan-weeks">${Array.from({length:p.weeks},(_,i)=>i+1).map(w=>`<section class="plan-week"><h3>Week ${w}</h3>${p.items.filter(x=>x.week===w).map(x=>`<article class="plan-session ${state.completed[x.id]?'is-done':''}"><label><input type="checkbox" data-plan-done="${x.id}" ${state.completed[x.id]?'checked':''}><span><strong>${esc(x.title)}</strong><small>${esc(x.note)} · ~${x.duration} min</small></span></label><button class="text-btn" data-plan-route="${esc(x.route)}">Start →</button></article>`).join('')}</section>`).join('')}</div>`;$$('[data-plan-done]',box).forEach(c=>c.onchange=()=>{state.completed[c.dataset.planDone]=c.checked;save();});$$('[data-plan-route]',box).forEach(b=>b.onclick=()=>route(b.dataset.planRoute));}
  function route(r){if(r.startsWith('weak:')){const rest=r.slice(5),i=rest.indexOf('|');window.TOEFL_APP?.openWeakness?.(rest.slice(0,i),rest.slice(i+1));return;}if(r.startsWith('clevel:')){nav('reachc');setTimeout(()=>window.CLEVEL_APP?.openModule?.(r.slice(7)),80);return;}if(r==='cplus:online'){nav('reachc','#onlineInteractionZone');return;}if(r==='cplus:mediation'){nav('reachc','#mediationStudioZone');return;}if(r==='cplus:portfolio'){nav('reachc','#portfolioZone');return;}if(r.startsWith('nav:')){nav(r.slice(4));return;}}

  // ---------- Mistake recycler ----------
  function renderRecycler(){const box=$('#mistakeRecycler');if(!box)return;const rows=weakToefl().slice(0,5);if(!rows.length){box.innerHTML='<p class="empty-state">No stable recurring weakness yet. Complete a few objective Reading/Listening items and the recycler will build itself from your error log.</p>';return;}box.innerHTML=rows.map(x=>{const mastered=x.acc>=.85,stable=x.acc>=.7;return `<article class="recycler-row"><div><span class="recycler-status ${mastered?'mastered':stable?'stabilising':'needs-work'}">${mastered?'MAINTAIN':stable?'STABILISING':'RECYCLE'}</span><strong>${esc(D.recyclerLabels[x.category]||x.category)}</strong><small>${esc(x.skill)} · ${Math.round(x.acc*100)}% recent/overall accuracy</small></div><button class="btn secondary small" data-recycle="${esc(x.skill)}|${esc(x.category)}">Train fresh item</button></article>`}).join('');$$('[data-recycle]',box).forEach(b=>b.onclick=()=>{const i=b.dataset.recycle.indexOf('|');window.TOEFL_APP?.openWeakness?.(b.dataset.recycle.slice(0,i),b.dataset.recycle.slice(i+1));});}

  // ---------- Productive studio + portfolio ----------
  const taskDims={oi1:['online','argumentation'],oi2:['online','argumentation'],oi3:['online','fluency'],oi4:['online','mediation'],oi5:['online','mediation'],oi6:['online','argumentation'],oi7:['online','fluency'],oi8:['online','nuance'],m1:['mediation','nuance'],m2:['mediation','precision'],m3:['mediation','precision'],m4:['mediation','synthesis'],m5:['mediation','fluency'],m6:['mediation','nuance'],m7:['mediation','precision'],m8:['mediation','synthesis']};
  function studioMarkup(x,type){const isOnline=type==='Online Interaction';const source=isOnline?`<div class="thread-box">${x.messages.map(m=>`<p>${esc(m)}</p>`).join('')}</div>`:`<div class="source-box"><p>${esc(x.source).replace(/\n/g,'<br>')}</p><small><strong>Audience:</strong> ${esc(x.audience)}</small></div>`;return `<div class="studio-head"><div><span class="tag ${isOnline?'indigo':'teal'}">${type.toUpperCase()}</span><h3>${esc(x.title)}</h3><p>${esc(x.context||'Adapt the source for the stated audience and purpose.')}</p></div><button class="text-btn" data-studio-next="${type}">Next task</button></div>${source}<div class="studio-goal"><strong>Your task</strong><p>${esc(x.goal)}</p></div><label class="draft-label"><strong>First attempt</strong><textarea class="writing-area" data-first placeholder="Write your first response before viewing strategy notes…"></textarea></label><button class="btn primary" data-lock-first>Lock first attempt & review</button><div class="studio-review hidden" data-review><div class="strategy-note"><strong>Strategy note</strong><p>${esc(x.strategy)}</p></div><div class="rubric-grid">${x.criteria.map((c,i)=>`<label><input type="checkbox" data-studio-check="${i}"> ${esc(c)}</label>`).join('')}</div><label class="draft-label"><strong>Revised attempt</strong><textarea class="writing-area" data-revised placeholder="Rewrite after reviewing the criteria. Make the changes visible in the text, not just in your reflection."></textarea></label><label class="draft-label"><strong>Reflection</strong><textarea class="reflection-area" data-reflection placeholder="What did you change, and why?"></textarea></label><button class="btn secondary" data-save-portfolio>Save both attempts to My C-Level Portfolio</button><div class="feedback" data-studio-feedback aria-live="polite"></div></div>`;}
  function wireStudio(box,x,type){const first=$('[data-first]',box),review=$('[data-review]',box),lock=$('[data-lock-first]',box);lock.onclick=()=>{if(first.value.trim().length<20){const f=document.createElement('p');f.className='feedback bad';f.textContent='Write a genuine first attempt before opening the review stage.';lock.insertAdjacentElement('afterend',f);setTimeout(()=>f.remove(),2200);return;}first.readOnly=true;lock.disabled=true;review.classList.remove('hidden');$('[data-revised]',box)?.focus();};$('[data-save-portfolio]',box).onclick=()=>{const revised=$('[data-revised]',box).value.trim(),reflection=$('[data-reflection]',box).value.trim();if(revised.length<20){$('[data-studio-feedback]',box).textContent='Write a revised attempt before saving.';$('[data-studio-feedback]',box).className='feedback bad';return;}const checks=$$('[data-studio-check]',box),score=checks.filter(c=>c.checked).length/checks.length*6;state.portfolio.push({id:`${x.id}-${Date.now()}`,type,title:x.title,dimensions:taskDims[x.id]||[],first:first.value.trim(),revised,reflection,score,date:new Date().toISOString()});state.portfolio=state.portfolio.slice(-30);window.TOEFL_APP?.markActivity?.();save();$('[data-save-portfolio]',box).disabled=true;$('[data-studio-feedback]',box).textContent=`Saved to portfolio · self-review ${score.toFixed(1)}/6`;$('[data-studio-feedback]',box).className='feedback good';};$$('[data-studio-next]',box).forEach(b=>b.onclick=()=>{if(type==='Online Interaction')state.onlineIndex=(state.onlineIndex+1)%D.onlineTasks.length;else state.mediationIndex=(state.mediationIndex+1)%D.mediationTasks.length;save();renderStudios();});}
  function renderStudios(){const o=$('#onlineWorkspace'),m=$('#mediationWorkspace');if(o){const x=D.onlineTasks[state.onlineIndex%D.onlineTasks.length];o.innerHTML=studioMarkup(x,'Online Interaction');wireStudio(o,x,'Online Interaction');}if(m){const x=D.mediationTasks[state.mediationIndex%D.mediationTasks.length];m.innerHTML=studioMarkup(x,'Mediation');wireStudio(m,x,'Mediation');}}
  function renderPortfolio(){const box=$('#portfolioList'),summary=$('#portfolioSummary');if(summary){const revised=state.portfolio.filter(x=>x.revised).length,scored=state.portfolio.filter(x=>Number.isFinite(x.score)),avg=scored.length?scored.reduce((s,x)=>s+x.score,0)/scored.length:null;summary.innerHTML=`<div><strong>${state.portfolio.length}</strong><span>saved evidence</span></div><div><strong>${revised}</strong><span>revised attempts</span></div><div><strong>${avg==null?'—':avg.toFixed(1)+'/6'}</strong><span>rubric self-review average</span></div>`;}if(!box)return;if(!state.portfolio.length){box.innerHTML='<p class="empty-state">Your portfolio is empty. Save an Online Interaction or Mediation Studio revision, or add evidence from any TOEFL/C-Level productive task.</p>';return;}box.innerHTML=[...state.portfolio].reverse().map(x=>`<article class="portfolio-entry"><header><div><span class="tag">${esc(x.type)}</span><h3>${esc(x.title)}</h3></div><button class="text-btn danger-text" data-delete-portfolio="${esc(x.id)}">Delete</button></header><div class="portfolio-meta">${x.dimensions.map(d=>`<span>${esc(d)}</span>`).join('')}${Number.isFinite(x.score)?`<b>${x.score.toFixed(1)}/6 self-review</b>`:'<b>revision evidence</b>'}</div><details><summary>Compare first and revised attempts</summary><div class="compare-grid"><div><strong>First attempt</strong><p>${esc(x.first)}</p></div><div><strong>Revised attempt</strong><p>${esc(x.revised)}</p></div></div>${x.reflection?`<p class="portfolio-reflection"><strong>Reflection:</strong> ${esc(x.reflection)}</p>`:''}</details></article>`).join('');$$('[data-delete-portfolio]',box).forEach(b=>b.onclick=()=>{state.portfolio=state.portfolio.filter(x=>x.id!==b.dataset.deletePortfolio);save();});}

  function saveManualPortfolio(){const type=$('#portfolioManualType')?.value||'Other',title=$('#portfolioManualTitle')?.value.trim()||'',dim=$('#portfolioManualDimension')?.value||'precision',first=$('#portfolioManualFirst')?.value.trim()||'',revised=$('#portfolioManualRevised')?.value.trim()||'',reflection=$('#portfolioManualReflection')?.value.trim()||'',feedback=$('#manualPortfolioFeedback');if(!title||first.length<20||revised.length<20){if(feedback){feedback.className='feedback bad';feedback.textContent='Add a task title plus a genuine first and revised attempt (at least 20 characters each).';}return;}state.portfolio.push({id:`manual-${Date.now()}`,type,title,dimensions:[dim],first,revised,reflection,score:null,date:new Date().toISOString()});state.portfolio=state.portfolio.slice(-30);window.TOEFL_APP?.markActivity?.();save();['#portfolioManualTitle','#portfolioManualFirst','#portfolioManualRevised','#portfolioManualReflection'].forEach(id=>{const el=$(id);if(el)el.value='';});if(feedback){feedback.className='feedback good';feedback.textContent='Saved locally to your C-Level Portfolio. Add self-review evidence through the task rubric when one is available.';}}
  function exportCsv(){const rows=[['Date','Type','Title','Dimensions','Self-review /6','First attempt','Revised attempt','Reflection'],...state.portfolio.map(x=>[x.date,x.type,x.title,x.dimensions.join('; '),Number.isFinite(x.score)?x.score.toFixed(1):'',x.first,x.revised,x.reflection])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`c-level-portfolio-${localDay()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);}

  function renderAll(){renderCefr();renderPlan();renderRecycler();renderPortfolio();}
  function init(){renderStudios();renderAll();const dateInput=$('#planTestDate');if(dateInput)dateInput.min=tomorrowDay();$('#generatePlan')?.addEventListener('click',buildPlan);$('#exportPortfolioCsv')?.addEventListener('click',exportCsv);$('#saveManualPortfolio')?.addEventListener('click',saveManualPortfolio);$$('[data-cplus-jump]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.cplusJump;if(a==='plan')nav('dashboard','#studyPlanZone');else nav('reachc','#'+a);}));}
  window.CPLUS_APP={exportState:()=>JSON.parse(JSON.stringify(state)),importState:x=>{state=merge(x);save();renderStudios();},reset:()=>{state=defaults();try{localStorage.removeItem(KEY)}catch{}renderStudios();renderAll();},refresh:renderAll};
  init();
})();
