window.TOEFL_DATA = {
  traps: [
    {title:"Hedge it, don't hide it",prompt:"Which sentence sounds most appropriately cautious in an academic discussion?",options:["This policy proves that remote learning is ineffective.","This policy may suggest that remote learning is less effective in some contexts.","Remote learning is obviously ineffective because the policy failed.","It is a fact that the policy makes remote learning ineffective."],answer:1,explanation:"C-level academic language often calibrates certainty. “may suggest” and “in some contexts” avoid an unsupported absolute claim."},
    {title:"Inference ≠ imagination",prompt:"A lecturer says: “The initial model was elegant, but it relied on assumptions the later field data simply did not support.” What is implied?",options:["The model was badly written.","The field data were probably fabricated.","The model's simplicity did not guarantee empirical validity.","The lecturer prefers theoretical work to fieldwork."],answer:2,explanation:"The contrast is between elegance and empirical support. Do not add attitudes or causes that were never stated."},
    {title:"Precision beats fancy words",prompt:"Choose the strongest C1/C2 revision: “A lot of researchers say the result is important.”",options:["Numerous researchers contend that the finding is significant.","Plentiful researchers vocalise the result's importance.","Many scientific people tell that the result matters hugely.","A multitude of researchers pronounce the result crucially."],answer:0,explanation:"Advanced writing is precise and idiomatic, not decorated. “contend” and “finding is significant” fit academic register."},
    {title:"Watch the scope",prompt:"Which statement is logically safest after reading that 68% of one university's respondents preferred hybrid classes?",options:["Most university students prefer hybrid classes.","Hybrid classes are preferred by students everywhere.","In this survey, a majority of respondents preferred hybrid classes.","The study proves that hybrid education is better."],answer:2,explanation:"Keep conclusions within the population and evidence actually described."},
    {title:"Reference words matter",prompt:"“The committee rejected the first proposal because it lacked a feasible timeline. This was later addressed in the revised plan.” What does “This” refer to?",options:["The committee","The rejection","The lack of a feasible timeline","The revised plan"],answer:2,explanation:"Track the precise problem carried forward into the next sentence."},
    {title:"Concession at C level",prompt:"Choose the most natural connector: “_____ the intervention improved attendance, its effect on attainment remained modest.”",options:["Despite","Although","Because of","Whereas of"],answer:1,explanation:"“Although” introduces a finite clause. “Despite” would require a noun phrase or -ing form."},
    {title:"Paraphrase the idea",prompt:"Original: “The decline was largely driven by higher transport costs.” Best paraphrase?",options:["The decline drove transport costs higher.","Rising transport costs accounted for much of the decline.","Transport costs declined because they were largely higher.","The decline and transport costs were mostly driving."],answer:1,explanation:"A good paraphrase preserves the causal relationship while changing structure and wording."},
    {title:"Listen for stance",prompt:"A speaker says: “I wouldn't go so far as to call the findings conclusive.” What is the stance?",options:["Strong rejection","Qualified reservation","Complete agreement","Irrelevance"],answer:1,explanation:"This is a classic softening move: the speaker is cautious, not fully dismissive."}
  ],
  diagnostic: [
    {skill:"reading",type:"text",q:"The phrase “a necessary but insufficient condition” means that the condition…",stimulus:"For urban tree planting to reduce heat exposure, canopy coverage is a necessary but insufficient condition; species selection, maintenance, and neighbourhood distribution also matter.",options:["guarantees the desired result by itself","is required, but cannot produce the result alone","is optional if other measures exist","becomes unnecessary once maintenance begins"],answer:1,why:"Necessary = required; insufficient = not enough on its own."},
    {skill:"reading",type:"text",q:"What can reasonably be inferred?",stimulus:"The new archive digitised thousands of manuscripts. Yet usage remained limited until librarians redesigned the search interface and added thematic pathways for non-specialists.",options:["Digitisation alone did not make the collection easily usable.","The manuscripts were unreadable before digitisation.","Specialists stopped using the archive after the redesign.","The archive contained too few manuscripts."],answer:0,why:"Access to content and usability are distinct; the second change increased use."},
    {skill:"reading",type:"text",q:"What is the author's main purpose?",stimulus:"Although early studies linked multitasking with productivity, many relied on self-reported performance. More recent experiments using task-switching measures have found substantial cognitive costs, especially when tasks require sustained attention.",options:["To prove all multitasking is harmful","To contrast earlier evidence with newer methodological findings","To describe how to design a questionnaire","To argue that self-reports are never useful"],answer:1,why:"The paragraph contrasts evidence bases and methods rather than making an absolute claim."},
    {skill:"reading",type:"cloze",q:"Complete the academic word.",stimulus:"The findings were not con_____ across age groups, which limits the study's generalisability.",options:["sistent","scious","secutive","ventional"],answer:0,why:"consistent = stable/similar across groups."},
    {skill:"reading",type:"text",q:"Which claim is supported?",stimulus:"In the first year, the programme reduced average waiting time by 11%. The reduction was larger in clinics that had already adopted electronic triage, but the study did not test whether triage caused the difference.",options:["Electronic triage caused the 11% reduction.","All clinics improved by exactly 11%.","The association with electronic triage should not be treated as causal evidence.","Clinics without electronic triage became slower."],answer:2,why:"The text explicitly warns that causation was not tested."},
    {skill:"reading",type:"text",q:"What does “nevertheless” signal here?",stimulus:"The sample was geographically narrow. Nevertheless, the authors argue that the mechanism they identified warrants testing in other regions.",options:["A cause","A concession followed by a continuing claim","A chronological sequence","A definition"],answer:1,why:"The writer acknowledges a limitation and then maintains a narrower claim."},

    {skill:"listening",type:"audio",audio:"I expected the seminar to focus on methodology, but the professor spent most of the session challenging the assumptions behind the model.",q:"What surprised the speaker?",options:["The seminar was cancelled.","The professor focused on assumptions rather than mainly on methodology.","The model had no assumptions.","The session was shorter than expected."],answer:1,why:"Listen to the contrast after “but”."},
    {skill:"listening",type:"audio",audio:"Could you send the revised abstract today? I'd like to circulate it before tomorrow's meeting.",q:"What is the speaker asking for?",options:["A meeting to be postponed","The revised abstract to be sent today","A new research topic","Permission to circulate a draft next week"],answer:1,why:"The time pressure is explicit: today, before tomorrow's meeting."},
    {skill:"listening",type:"audio",audio:"The term sounds straightforward, but in ecology resilience doesn't simply mean returning to the exact previous state. A system may reorganise and still preserve its core functions.",q:"What point is the lecturer making?",options:["Ecological resilience has a broader meaning than simple restoration.","Ecosystems always return to their former state.","Core functions are irrelevant to resilience.","Reorganisation proves ecosystem failure."],answer:0,why:"The lecturer redefines the concept beyond a common interpretation."},
    {skill:"listening",type:"audio",audio:"I can see why the department wants a single assessment rubric. My concern is that a uniform rubric might reward consistency at the expense of disciplinary nuance.",q:"What is the speaker's attitude?",options:["Unqualified support","Qualified concern","Complete indifference","Anger about grading"],answer:1,why:"“I can see why… My concern is…” signals partial acknowledgement followed by reservation."},
    {skill:"listening",type:"audio",audio:"The museum will remain open during the renovation, although the east gallery will be inaccessible from Monday through Thursday. Visitors should enter through the courtyard during that period.",q:"What should visitors do Monday through Thursday?",options:["Avoid the museum entirely","Use the courtyard entrance","Enter through the east gallery","Come only in the evening"],answer:1,why:"The announcement gives a temporary alternative entrance."},
    {skill:"listening",type:"audio",audio:"At first, researchers assumed the birds were responding to temperature. That explanation became less convincing when the same behaviour appeared during unusually cool seasons. Attention then shifted to day length.",q:"Why did researchers reconsider the temperature explanation?",options:["The birds disappeared in cool seasons.","The behaviour persisted when temperatures were unusually low.","Day length stopped changing.","Temperature measurements were unavailable."],answer:1,why:"The observation contradicted what a temperature-only explanation would predict."},

    {skill:"speaking",type:"text",q:"Which opening best answers an interview question asking whether universities should require community service?",stimulus:"You have very little time. Choose the response that is direct, nuanced and easy to develop.",options:["Community service is a very interesting topic in modern society.","Yes, in some programmes it can be valuable, provided that students have genuine choice in how they contribute.","There are many advantages and disadvantages and I will explain them.","Since the dawn of time, communities have depended on service."],answer:1,why:"It answers immediately and builds in nuance, creating a clear path for development."},
    {skill:"speaking",type:"text",q:"Which version sounds most fluent and precise?",stimulus:"You want to disagree politely with an interviewer's claim.",options:["No, this is false and I disagree totally.","I see the logic behind that view, but I think it underestimates the role of access.","I am not agree because access is a thing.","On the contrary of you, access makes a difference maybe."],answer:1,why:"It acknowledges the other view and states a precise reservation with natural phrasing."},
    {skill:"speaking",type:"text",q:"Which signposting is least formulaic and most useful?",stimulus:"You are explaining why a policy had an unexpected effect.",options:["Firstly I will talk about my first point, secondly my second point.","The key reason is probably timing; more specifically, the policy arrived after most budgets had already been set.","I have two ideas because there are two ideas.","My first argumentation concerns the following point."],answer:1,why:"Natural spoken signposting highlights the relationship between ideas rather than announcing a memorised template."},
    {skill:"speaking",type:"text",q:"Choose the best repair strategy if you lose a word while speaking.",stimulus:"You cannot remember the word “subsidy”.",options:["Stop for ten seconds until the word returns.","Switch to French.","Paraphrase: “financial support provided by the government”.","Say “the thing” repeatedly."],answer:2,why:"C-level speakers can maintain flow by paraphrasing precisely."},
    {skill:"speaking",type:"text",q:"Which sentence uses emphasis naturally in speech?",stimulus:"You want the listener to understand that implementation—not design—was the main issue.",options:["The DESIGN was not the main problem; the IMPLEMENTATION was.","The design was not the main problem the implementation was maybe.","The main problem was problematically implementation.","Implementation design problem main."],answer:0,why:"Contrastive stress can make the information structure immediately clear."},
    {skill:"speaking",type:"text",q:"Which answer best shows C-level qualification?",stimulus:"Question: Does technology always improve learning?",options:["Yes, technology always makes learning better.","No, technology is bad for education.","Not necessarily. Its effect depends on how deliberately it is integrated into the learning task.","Technology has pros and cons, that's all."],answer:2,why:"The answer rejects the absolute premise and replaces it with a precise condition."},

    {skill:"writing",type:"text",q:"Choose the best sentence for an academic discussion.",stimulus:"You want to claim that a study is useful despite a limited sample.",options:["The study is perfect although the sample is bad.","Despite its limited sample, the study offers a useful basis for generating hypotheses.","Although of a limited sample, the study gives useful things.","The limited sample proves hypotheses usefully."],answer:1,why:"The sentence concedes the limitation while making a proportionate claim."},
    {skill:"writing",type:"text",q:"Which email sentence is most appropriate?",stimulus:"You need to ask a university administrator to clarify a deadline.",options:["Tell me the real deadline ASAP.","I would be grateful if you could confirm whether the deadline applies to supporting documents as well as the online form.","I want you to explain because the website is confusing me.","Can you clarify it???"],answer:1,why:"Polite, specific and efficient."},
    {skill:"writing",type:"text",q:"Which sentence has the clearest logical relationship?",stimulus:"You need to contrast short-term cost with long-term benefit.",options:["The scheme is expensive, and therefore it saves money later although.","Although the scheme requires substantial initial investment, it may reduce long-term operating costs.","The scheme costs and long term is benefit.","Despite the scheme requires money, it reduces perhaps costs because long term."],answer:1,why:"Correct concession structure plus calibrated claim."},
    {skill:"writing",type:"text",q:"Choose the strongest paraphrase.",stimulus:"Original: “Students who receive rapid feedback are more likely to revise strategically.”",options:["Students receiving timely feedback tend to make more purposeful revisions.","Students who get rapid feedback are more likely to revise strategically.","Rapid feedback students revise more strategically because they get feedback.","Feedback is rapid and students revise."],answer:0,why:"It changes both vocabulary and structure while preserving meaning."},
    {skill:"writing",type:"text",q:"Which version avoids an unsupported generalisation?",stimulus:"You are discussing one study conducted with first-year engineering students.",options:["All students learn better in teams.","The findings suggest that structured teamwork may benefit students in similar first-year engineering contexts.","Teamwork definitely improves university education.","Engineering students everywhere need teams."],answer:1,why:"It keeps the scope aligned with the evidence."},
    {skill:"writing",type:"text",q:"Which sentence is most cohesive?",stimulus:"Previous sentence: “The intervention increased attendance but did not improve exam scores.”",options:["This divergence suggests that participation and attainment should be analysed separately.","Attendance exam scores intervention is different.","However and therefore scores are attendance.","This proves attendance has no relationship with learning ever."],answer:0,why:"“This divergence” accurately packages the contrast and develops its implication."}
  ],
  reading: {
    word:[
      {stem:"The committee described the evidence as incon_____ and requested a larger follow-up study.",options:["clusive","venient","sistent","siderate"],answer:0,why:"inconclusive = not strong enough to support a definite conclusion."},
      {stem:"The new protocol was implemented grad_____, allowing staff to adapt without disrupting services.",options:["ually","ient","ation","ified"],answer:0,why:"gradually is the adverb required after “implemented”."},
      {stem:"Researchers should disting_____ between correlation and causation when interpreting observational data.",options:["uish","ress","ulate","ressure"],answer:0,why:"distinguish between A and B is the correct collocation."},
      {stem:"The authors acknowl_____ that the sample may not represent rural populations.",options:["edge","ish","ment","able"],answer:0,why:"acknowledge = explicitly recognise a fact or limitation."},
      {stem:"The policy's long-term impact remains uncert_____, partly because implementation differs across regions.",options:["ain","ify","ainty","ained"],answer:0,why:"uncertain is the adjective complement after “remains”."},
      {stem:"The apparent contradiction can be res_____ if the two studies are understood to measure different outcomes.",options:["olved","erved","isted","ourced"],answer:0,why:"resolve a contradiction = explain or remove the conflict."}
    ],
    daily:[
      {text:"LIBRARY NOTICE — The fourth-floor silent study area will close at 18:00 on Wednesday for ventilation maintenance. Students needing quiet study after 18:00 may use Seminar Rooms 2–4 on the ground floor. Group work remains prohibited in those rooms during this temporary arrangement.",q:"What is true on Wednesday evening?",options:["All ground-floor rooms are closed.","Students may use certain seminar rooms for quiet individual study.","Group work is moved to the fourth floor.","The ventilation work affects the entire library."],answer:1,why:"The alternative rooms are available, but the quiet-study rule remains."},
      {text:"COURSE UPDATE — Because the guest speaker cannot travel on 14 October, the policy workshop will take place as scheduled but will use the case-study format originally planned for Week 7. The guest session has been moved to 28 October. No preparation task is due for the workshop this week.",q:"What changed?",options:["The 14 October class was cancelled.","The case study has been removed from the course.","The guest session was postponed, while the class itself remains scheduled.","Students must submit the Week 7 task early."],answer:2,why:"Separate the class date from the guest speaker's date."},
      {text:"RESEARCH PARTICIPANTS — Please arrive ten minutes before your allocated slot. If you are more than five minutes late, we may need to reschedule because the calibration procedure cannot be shortened. Reimbursement forms are completed after participation, not at reception.",q:"Why might a late participant need to reschedule?",options:["The reimbursement office closes early.","The calibration procedure requires its full duration.","Reception does not accept late arrivals.","Participants must arrive with completed forms."],answer:1,why:"The reason is explicitly tied to the procedure's fixed duration."}
    ],
    academic:[
      {title:"When efficiency creates fragility",text:"For much of the twentieth century, supply-chain management treated efficiency as the reduction of visible slack. Firms shortened inventories, concentrated suppliers, and synchronised deliveries so that materials arrived close to the moment they were needed. These practices reduced storage costs and often improved short-term productivity. Yet they also removed forms of redundancy that had previously absorbed disruption. A second supplier, a larger inventory, or spare production capacity could appear wasteful under stable conditions while becoming valuable during a shock.\n\nRecent research therefore distinguishes efficiency from resilience rather than assuming that the two are opposites on a single scale. A resilient system may still be highly efficient, but its efficiency is evaluated across a wider range of conditions. The relevant question is not simply how little spare capacity a network can maintain, but how rapidly it can detect disruption, redirect flows, and recover essential functions. This reframing has encouraged organisations to treat redundancy as a strategic resource when its cost is lower than the expected cost of failure.",questions:[
        {q:"What is the main contrast in the passage?",options:["Storage and transport","Short-term efficiency and resilience across disruptions","Large and small firms","Manufacturing and services"],answer:1,why:"The passage reframes efficiency by considering performance under disruption."},
        {q:"Why does the author mention a second supplier?",options:["As an example of apparently wasteful redundancy that may provide resilience","To argue that firms should always double their suppliers","To show that suppliers cause inventory costs","As evidence that synchronised delivery is impossible"],answer:0,why:"It exemplifies capacity that looks inefficient in stable conditions but is valuable in a shock."},
        {q:"What does “This reframing” refer to?",options:["Eliminating all spare capacity","Evaluating efficiency across a broader set of conditions","Returning to twentieth-century storage practices","Measuring only visible costs"],answer:1,why:"The preceding sentences redefine how efficiency should be assessed."}
      ]},
      {title:"The problem with proxy measures",text:"Researchers frequently measure an elusive concept by using a proxy: an observable variable assumed to stand in for something more difficult to capture directly. Citation counts, for instance, may be used as a proxy for scholarly influence. Proxies make large-scale comparison possible, but they can also reshape the behaviour they were intended merely to observe. Once a proxy becomes a target, individuals and institutions have incentives to optimise the measure itself.\n\nThis does not make proxies useless. Rather, it changes the question researchers should ask. A useful proxy must be evaluated not only for its correlation with the underlying concept, but also for how that relationship changes when people know the proxy matters. Measures embedded in high-stakes decisions may become less informative precisely because actors adapt strategically to them. The challenge, therefore, is institutional as much as statistical.",questions:[
        {q:"What is the author's central claim?",options:["All proxies should be abandoned.","Proxy measures can change behaviour and therefore must be evaluated in context.","Citation counts perfectly measure scholarly influence.","Statistical correlation is irrelevant."],answer:1,why:"The passage argues for contextual evaluation, not rejection."},
        {q:"Why may a proxy become less informative in high-stakes settings?",options:["Because the concept stops existing","Because actors may optimise the measure itself","Because correlations always become negative","Because institutions refuse to collect data"],answer:1,why:"Strategic adaptation can weaken the proxy-concept relationship."}
      ]}
    ]
  },
  listening:{
    response:[
      {audio:"Didn't the ethics committee ask for one more revision?",options:["Yes, we're submitting it this afternoon.","The committee meets in Building One.","Ethics is an important field."],answer:0,why:"A yes/no question about a requested revision needs a relevant status response."},
      {audio:"Would you mind moving the presentation to the end of the session?",options:["Not at all, I can go last.","The presentation had twelve slides.","I moved here last year."],answer:0,why:"“Would you mind…?” is a polite request; “Not at all” accepts it."},
      {audio:"How come the pilot study was extended?",options:["Because recruitment took longer than expected.","For another six weeks.","At the clinical research centre."],answer:0,why:"“How come” asks for a reason."}
    ],
    conversation:[
      {audio:"Student: I saw that the data workshop is full, but I need it before I start my dissertation analysis. Administrator: The registration page is full, yes, but two reserved places are released forty-eight hours before each session if doctoral students haven't used them. Student: So I should keep checking online? Administrator: Exactly. And if nothing opens, email us by Friday; we're considering an extra session.",q:"What does the administrator suggest the student do first?",options:["Email immediately","Keep checking the registration page","Contact doctoral students","Postpone the dissertation"],answer:1,why:"The immediate suggestion is to monitor the page; email is the fallback."},
      {audio:"Researcher: The sensor readings look much noisier than last week. Technician: I noticed that too. Before we recalibrate everything, check whether the protective cover was replaced after cleaning. Researcher: Would that affect the readings this much? Technician: If it's slightly misaligned, yes. It's the quickest thing to rule out.",q:"Why does the technician mention the protective cover?",options:["To propose a quick possible explanation for the noisy data","To blame the researcher for cleaning the sensor","To recommend buying a new sensor","To explain last week's calibration"],answer:0,why:"The cover is a low-cost cause to check before full recalibration."}
    ],
    announcement:[
      {audio:"Attention students: tomorrow's careers fair will open at ten as planned, but employer presentations scheduled for the main auditorium will begin thirty minutes later because of a technical inspection. Exhibition stands in the central hall are unaffected. Students registered for the ten-fifteen presentation should therefore arrive at ten-forty-five.",q:"Which activity is delayed?",options:["The opening of the careers fair","Employer presentations in the auditorium","Exhibition stands in the central hall","All student registration"],answer:1,why:"Only auditorium presentations shift by thirty minutes."},
      {audio:"Due to resurfacing work, the north bicycle entrance will be closed until Friday evening. Cyclists may use the west gate, where temporary racks have been installed beside the security office. Please do not leave bicycles along the emergency access road.",q:"What are cyclists instructed to do?",options:["Use the north entrance before Friday","Park beside the emergency road","Use the west gate and temporary racks","Leave bicycles at home"],answer:2,why:"The announcement provides a specific alternative route and parking area."}
    ],
    talk:[
      {audio:"In behavioural economics, default options are often discussed as if they simply remove effort from a decision. That's part of the story, but not all of it. A default can also communicate what an institution considers normal or recommended. Imagine two identical pension plans. In one workplace, employees are automatically enrolled and can opt out. In another, they must actively enrol. Participation is usually higher in the first case. Some of that difference reflects inertia, but some may reflect interpretation: employees can read automatic enrolment as a signal that participation is expected or beneficial. This matters when we evaluate policy. If a default works partly through social meaning, moving the same default into a different institutional culture may produce a different effect.",q:"What is the lecturer's main point?",options:["Default options work only because people are lazy.","The effect of defaults may depend partly on the social meaning they communicate.","Pension plans should never use automatic enrolment.","Institutional culture has no effect on decisions."],answer:1,why:"The talk expands the mechanism from inertia to interpretation and context."},
      {audio:"One reason urban heat is difficult to map is that temperature varies sharply over small distances. A weather station at an airport may accurately describe regional conditions while missing the heat experienced on a treeless street several kilometres away. Researchers increasingly combine fixed sensors with mobile measurements taken by bicycles or vehicles. The mobile data provide finer spatial detail, but they introduce another problem: measurements taken at different times cannot be compared as if conditions were identical. Good heat maps therefore require both spatial coverage and careful temporal adjustment.",q:"Why are mobile measurements useful but challenging?",options:["They are cheaper but always inaccurate.","They improve spatial detail but may be collected under different time conditions.","They measure only airport temperatures.","They eliminate the need for fixed sensors."],answer:1,why:"The final two sentences state the trade-off directly."}
    ]
  },
  speaking:{
    repeat:[
      "The apparent decline may reflect a change in measurement rather than a genuine change in behaviour.",
      "Although the intervention was inexpensive, its effects varied considerably across neighbourhoods.",
      "Researchers were particularly interested in whether the pattern persisted after controlling for age.",
      "The committee recommended further analysis before the findings were used to guide policy.",
      "A plausible explanation is that participants interpreted the instructions differently from what the researchers intended.",
      "The evidence is consistent with the hypothesis, but it does not establish causation.",
      "What initially appeared to be a technical problem turned out to be a disagreement about definitions.",
      "Students who received targeted feedback revised more extensively than those who received only a numerical score."
    ],
    interview:[
      {q:"Some universities are reducing the number of large lectures. Do you think this is a good change?",follow:"Give a clear position, one reason, and one concrete example or limitation."},
      {q:"Should students be allowed to use generative AI for assessed coursework?",follow:"Define the conditions under which your answer changes."},
      {q:"Which matters more in group projects: choosing your teammates or receiving a clear role?",follow:"Compare the two rather than discussing only one."},
      {q:"Is it better to specialise early at university or keep a broad curriculum for longer?",follow:"Acknowledge one advantage of the alternative view."},
      {q:"Should cities prioritise public transport even if car journeys become less convenient?",follow:"State a position and qualify it with a realistic condition."},
      {q:"Can online discussion be as intellectually valuable as face-to-face discussion?",follow:"Avoid an absolute yes/no; explain what makes the difference."},
      {q:"What is one university rule you would redesign, and why?",follow:"Describe the problem, the change, and one possible unintended consequence."},
      {q:"Do rankings help students choose universities effectively?",follow:"Distinguish what rankings measure well from what they may miss."}
    ]
  },
  writing:{
    sentence:[
      {words:["although","the sample","was relatively small","the pattern","was consistent","across three sites"],answer:"Although the sample was relatively small, the pattern was consistent across three sites."},
      {words:["the findings","should be interpreted cautiously","because","the study","did not include","a control group"],answer:"The findings should be interpreted cautiously because the study did not include a control group."},
      {words:["not only","did the intervention","reduce waiting times","but it also","improved","staff satisfaction"],answer:"Not only did the intervention reduce waiting times, but it also improved staff satisfaction."},
      {words:["whether","the policy succeeds","will depend partly on","how consistently","it is implemented","across regions"],answer:"Whether the policy succeeds will depend partly on how consistently it is implemented across regions."}
    ],
    email:[
      {situation:"You registered for a university research workshop, but the confirmation email lists the wrong session. Write to the organiser. Ask them to confirm your correct session and explain why the timing matters.",recipient:"Workshop organiser",goal:"polite clarification + concise reason",model:"Dear Workshop Team,\n\nThank you for confirming my registration. I noticed that the email lists the Thursday afternoon session, whereas I selected the Friday morning session when I registered. Could you please confirm which session I am currently booked for?\n\nThe timing matters because I have a compulsory seminar on Thursday afternoon. If possible, I would therefore be grateful to remain in the Friday group.\n\nMany thanks for your help.\nBest regards,"},
      {situation:"A lecturer has shared a dataset, but one variable is not defined in the documentation. Write to ask for clarification before you begin your analysis.",recipient:"Lecturer",goal:"specific question + why it matters",model:"Dear Dr Taylor,\n\nThank you for sharing the dataset. Before I begin the analysis, could I clarify the variable labelled “engagement_total”? I could not find its definition in the accompanying documentation, and I am unsure whether it combines attendance and online activity or refers to online activity only.\n\nKnowing how the variable was constructed will help me avoid interpreting the results incorrectly.\n\nThank you in advance for your clarification.\nBest regards,"}
    ],
    discussion:[
      {teacher:"Professor: Some universities are considering replacing a portion of final exams with frequent low-stakes assessment. Would this improve learning?",studentA:"Mina: Yes. Regular assessment encourages students to study throughout the semester rather than cramming.",studentB:"Leo: I'm not convinced. Too many assessments can create constant pressure and reduce time for deeper work.",prompt:"Write your contribution. Take a clear position, respond to at least one idea already raised, and add a new reason or distinction.",model:"I agree with Mina that frequent low-stakes assessment can improve the distribution of study time, but Leo's concern depends on how “frequent” is defined. If every task carries a deadline and detailed grading, the system may simply replace one form of pressure with another. A better approach would be short assessments that provide rapid feedback while contributing only modestly to the final grade. Their main purpose should be diagnostic: helping students identify misconceptions early enough to correct them before major assignments or exams."},
      {teacher:"Professor: Should universities require all students to take at least one course outside their main discipline?",studentA:"Ana: Yes. It helps students make connections between fields and can improve creativity.",studentB:"Marcus: Students already have limited time, so compulsory breadth can prevent them from developing expertise.",prompt:"Write your contribution. Address the trade-off between breadth and depth.",model:"Marcus is right that compulsory breadth has an opportunity cost, especially in programmes with heavy professional requirements. However, that does not mean cross-disciplinary study has to compete directly with expertise. A carefully designed course could complement the main discipline—for example, data ethics for computer scientists or communication for health students. I would therefore support a requirement only if students can choose from options that create a meaningful connection with their primary field rather than simply adding an unrelated elective."}
    ]
  },
  vocabulary:[
    ["ambiguous","/æmˈbɪɡjuəs/","open to more than one interpretation","ambigu / équivoque","The wording is ambiguous enough to support two plausible readings."],
    ["bolster","/ˈbəʊlstə(r)/","to strengthen or support something","renforcer / étayer","The additional data bolster the argument without proving it conclusively."],
    ["caveat","/ˈkæviæt/","a warning or limitation that should be considered","réserve / mise en garde","The conclusion is useful, with the caveat that the sample was small."],
    ["coherent","/kəʊˈhɪərənt/","logical and well organised","cohérent","A coherent response makes the relationship between ideas explicit."],
    ["compelling","/kəmˈpelɪŋ/","very convincing or persuasive","convaincant","The longitudinal evidence is more compelling than the anecdotal examples."],
    ["concede","/kənˈsiːd/","to admit that a point is true, often reluctantly","concéder / reconnaître","The author concedes that the policy may impose short-term costs."],
    ["constrain","/kənˈstreɪn/","to limit what is possible","contraindre / limiter","Budget rules constrain the range of feasible interventions."],
    ["counterintuitive","/ˌkaʊntərɪnˈtjuːɪtɪv/","contrary to what one would naturally expect","contre-intuitif","The counterintuitive result disappeared in the larger sample."],
    ["credible","/ˈkredəbəl/","able to be believed or trusted","crédible","A credible explanation must account for the timing of the change."],
    ["derive","/dɪˈraɪv/","to obtain something from a source","tirer / dériver","The estimate is derived from three independent datasets."],
    ["discrepancy","/dɪˈskrepənsi/","a difference between things expected to agree","écart / divergence","The discrepancy may result from different sampling methods."],
    ["elicit","/ɪˈlɪsɪt/","to cause or draw out a response or information","susciter / obtenir","The interviewer used follow-up questions to elicit more precise answers."],
    ["empirical","/ɪmˈpɪrɪkəl/","based on observation or experiment","empirique","The theory is elegant but lacks strong empirical support."],
    ["feasible","/ˈfiːzəbəl/","possible and practical to do","réalisable","The proposal is technically feasible but financially demanding."],
    ["fluctuate","/ˈflʌktʃueɪt/","to rise and fall irregularly","fluctuer","Participation rates fluctuate considerably across semesters."],
    ["framework","/ˈfreɪmwɜːk/","a structure of ideas used to organise analysis","cadre conceptuel","The framework distinguishes individual from institutional factors."],
    ["infer","/ɪnˈfɜː(r)/","to reach a conclusion from evidence rather than explicit statement","déduire / inférer","We can infer that timing affected the outcome, but not that it was the only cause."],
    ["inherent","/ɪnˈhɪərənt/","existing as a natural or essential feature","inhérent","Some uncertainty is inherent in long-term forecasting."],
    ["mitigate","/ˈmɪtɪɡeɪt/","to reduce the severity or harmful effect of something","atténuer","Targeted subsidies may mitigate the impact on low-income households."],
    ["nuanced","/ˈnjuːɑːnst/","showing subtle distinctions rather than simple oppositions","nuancé","A nuanced answer recognises both the benefit and the limitation."],
    ["plausible","/ˈplɔːzəbəl/","seeming reasonable or likely to be true","plausible","Several plausible mechanisms could explain the association."],
    ["preliminary","/prɪˈlɪmɪnəri/","coming before a more complete or final stage","préliminaire","Preliminary findings should not be treated as definitive."],
    ["robust","/rəʊˈbʌst/","strong and reliable across different conditions or analyses","robuste / solide","The relationship remained robust after several sensitivity checks."],
    ["salient","/ˈseɪliənt/","particularly noticeable or important","saillant / particulièrement pertinent","Cost was the most salient concern raised by participants."],
    ["scope","/skəʊp/","the range or extent covered by an activity or claim","portée / champ","The claim goes beyond the scope of the evidence presented."],
    ["substantiate","/səbˈstænʃieɪt/","to support a claim with evidence","étayer / justifier","The report does not substantiate its strongest causal claim."],
    ["tentative","/ˈtentətɪv/","not certain or final","provisoire / prudent","The authors offer a tentative explanation for the unexpected pattern."],
    ["underpin","/ˌʌndəˈpɪn/","to provide the basis or support for something","sous-tendre / fonder","Several assumptions underpin the model's predictions."],
    ["viable","/ˈvaɪəbəl/","capable of working successfully","viable","The approach is viable only if reliable data are available."],
    ["warrant","/ˈwɒrənt/","to justify or make an action appropriate","justifier","The preliminary result warrants further investigation."],
    ["account for","/əˈkaʊnt fɔː(r)/","to explain or form a particular proportion of something","expliquer / représenter","Seasonal variation may account for part of the difference."],
    ["by contrast","/baɪ ˈkɒntrɑːst/","used to introduce a clear difference","en revanche / par contraste","The first group improved; by contrast, the control group remained stable."],
    ["insofar as","/ˌɪnsəʊˈfɑːr æz/","to the extent that","dans la mesure où","The policy is effective insofar as local authorities can enforce it."],
    ["notwithstanding","/ˌnɒtwɪðˈstændɪŋ/","despite something","malgré / nonobstant","Notwithstanding these limitations, the study raises an important question."],
    ["predominantly","/prɪˈdɒmɪnəntli/","mainly or mostly","principalement","The sample was predominantly composed of first-year students."],
    ["thereby","/ˌðeəˈbaɪ/","as a result of that action","ce faisant / par là même","The redesign shortened the form, thereby reducing completion time."],
    ["whereas","/weərˈæz/","used to contrast two facts","tandis que","The first measure captures frequency, whereas the second captures intensity."],
    ["yield","/jiːld/","to produce a result","produire / donner","The revised model yielded more stable estimates."],
    ["adverse","/ˈædvɜːs/","harmful or unfavourable","défavorable / nocif","The policy had no measurable adverse effect on retention."],
    ["allocate","/ˈæləkeɪt/","to distribute resources for a purpose","allouer","Funds were allocated according to population size."],
    ["corroborate","/kəˈrɒbəreɪt/","to provide additional evidence that supports a statement","corroborer","Independent records corroborate the participants' accounts."],
    ["detrimental","/ˌdetrɪˈmentəl/","causing harm or damage","préjudiciable","Excessive workload can be detrimental to sustained learning."],
    ["equivocal","/ɪˈkwɪvəkəl/","uncertain or open to more than one interpretation","équivoque / ambigu","The evidence remains equivocal, so strong conclusions would be premature."],
    ["marginal","/ˈmɑːdʒɪnəl/","small in effect or importance","marginal","The second intervention produced only a marginal improvement."],
    ["proponent","/prəˈpəʊnənt/","a person who supports an idea or proposal","partisan / défenseur","Proponents argue that the reform improves access."],
    ["reconcile","/ˈrekənsaɪl/","to show how apparently conflicting ideas can both be true","concilier","The review attempts to reconcile the two apparently contradictory findings."],
    ["rigorous","/ˈrɪɡərəs/","extremely thorough and careful","rigoureux","A rigorous comparison requires equivalent baseline measures."],
    ["threshold","/ˈθreʃhəʊld/","a level at which something begins to happen or change","seuil","The effect appeared only above a certain exposure threshold."]
  ],
  lab:{
    hedging:[
      {q:"Choose the best academic revision: “This proves that social media causes anxiety.”",options:["This proves totally that social media causes anxiety.","These findings suggest a possible association between social media use and anxiety.","Social media might perhaps definitely cause anxiety.","Anxiety is caused by social media according to everything."],answer:1,why:"The evidence is reframed as an association unless the design truly establishes causality."},
      {q:"Which phrase expresses the strongest but still qualified confidence?",options:["might possibly","appears to","is highly likely to","could conceivably"],answer:2,why:"“Highly likely” is strong confidence without claiming certainty."}
    ],
    nominalisation:[
      {q:"Best concise academic rewrite: “When the researchers implemented the policy, participation increased.”",options:["The implementation of the policy was associated with increased participation.","The researchers implementing policy participation increased it.","Policy implementation did participation increase.","When implementation happened, increase was participation."],answer:0,why:"The nominalisation is grammatical and compact, while “associated with” avoids overclaiming causation."},
      {q:"Which sentence is too nominalised and difficult to process?",options:["The evaluation identified two limitations.","The implementation of the prioritisation of the allocation of resources required reconsideration.","Resource allocation required further review.","The team reconsidered how resources were allocated."],answer:1,why:"Nominalisation can increase density but excessive stacking reduces clarity."}
    ],
    complex:[
      {q:"Choose the correct concessive structure.",options:["Despite the sample was small, the pattern was consistent.","Although the sample was small, the pattern was consistent.","Despite of the small sample, the pattern was consistent.","Although of being small, the sample pattern was consistent."],answer:1,why:"Although + clause; despite + noun phrase / -ing."},
      {q:"Which sentence controls the relationship most clearly?",options:["The measure is cheap, it is inaccurate, researchers use it.","Although the measure is inexpensive, its limited accuracy makes it unsuitable for high-stakes decisions.","The measure although cheap and inaccurate and decisions.","Inexpensive because inaccurate, the measure is used high stakes."],answer:1,why:"The subordinate clause establishes concession and the main clause carries the judgement."}
    ],
    paraphrase:[
      {q:"Original: “The intervention had little effect on participants who were already highly active.”",options:["Participants with high baseline activity showed only limited change following the intervention.","The intervention had little effect on participants who were already highly active.","Active participants had intervention but little effects active.","Highly active people were not participants."],answer:0,why:"The idea is preserved with changed structure and vocabulary."},
      {q:"Which is NOT a safe paraphrasing strategy?",options:["Change sentence structure","Use an accurate synonym","Change the logical relationship to sound different","Combine or split clauses while preserving meaning"],answer:2,why:"A paraphrase must preserve the original meaning and logic."}
    ],
    stance:[
      {q:"“The explanation is attractive, but the evidence remains incomplete.” What stance is expressed?",options:["Unqualified endorsement","Qualified scepticism","Complete rejection","Neutral chronology"],answer:1,why:"Positive acknowledgement is followed by a limitation."},
      {q:"Best phrase to introduce a limitation without dismissing a study?",options:["This study is useless because…","A limitation worth noting is…","Obviously the researchers failed to…","The study proves nothing since…"],answer:1,why:"It flags a limitation proportionately."}
    ],
    cohesion:[
      {q:"Previous idea: “The two groups improved by similar amounts, but they began at very different baseline levels.” Best next sentence?",options:["This baseline difference complicates direct comparison of their final scores.","Moreover baseline and final are groups.","However they improved because difference.","This proves that the groups were the same."],answer:0,why:"The noun phrase “This baseline difference” creates precise reference and logical progression."},
      {q:"Which connector fits? “The intervention improved attendance. _____, exam performance did not change significantly.”",options:["Similarly","However","Therefore","For example"],answer:1,why:"The second outcome contrasts with the first."}
    ]
  }
};
